CREATE TABLE mysubj (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    subj VARCHAR(30) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
CREATE TABLE myassign (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    subj VARCHAR(30) NOT NULL,
    activity VARCHAR(150) NOT NULL,
    duedate VARCHAR(20) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    fullname VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    imgloc VARCHAR(100),
    bday VARCHAR(15),
    phone VARCHAR(15),
    bio VARCHAR(100),
    branch VARCHAR(30),
    city VARCHAR(30),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);