CREATE TABLE mysubj (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    subj VARCHAR(30) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
CREATE TABLE myassign (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    subj VARCHAR(30) NOT NULL,
    activity VARCHAR(150) NOT NULL,
    duedate VARCHAR(20) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);